# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
import os

def build(bld):
    all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES'] + bld.env['NS3_ENABLED_CONTRIBUTED_MODULES']]
    for filename in os.listdir(str(bld.path)+'/spdash'):
        if not filename.endswith(".cc"):
            continue
        name = filename[:-len(".cc")]
        obj = bld.create_ns3_program(name, all_modules)
        obj.source = 'spdash/'+filename

    
    for filename in os.listdir(str(bld.path)+'/dash'):
        if filename.startswith("cttc-") or not filename.endswith(".cc"):
            continue
        name = filename[:-len(".cc")]
        obj = bld.create_ns3_program(name, all_modules)
        obj.source = 'dash/'+filename
