# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('endash', ['internet','config-store','stats', 'mobility'])
    module.source = [
#         'model/circular-buffer.cc',
        'model/http/http-common-request-response.cc',
        'model/http/http-server-base-request-handler.cc',
        'model/http/http-server-simple-request-handler.cc',
        'model/http/http-server.cc',
        
        'model/http/http-client-collection.cc',
        'model/http/http-client-basic.cc',

        'model/dash/dash-request-handler.cc',
        'model/dash/endash-video-player.cc',
        
        'model/mobility/constant-speed-zigzag-box-mobility-model.cc',
        'model/propagation/log-normal-distance-propagation-loss-model.cc',
        
        'helper/http-helper.cc',
        'helper/endash-helper.cc',
        ]

#     module_test = bld.create_ns3_module_test_library('spdash')
#     module_test.source = [
# #         'test/spdash-test-suite.cc',
#         ]

    headers = bld(features='ns3header')
    headers.module = 'endash'
    headers.source = [
        'model/util/nlohmann_json.h',
#         'model/circular-buffer.h',
        'model/http/ext-callback.h',
        'model/http/http-common.h',
        'model/http/http-common-request-response.h',
        
        'model/http/http-server-base-request-handler.h',
        'model/http/http-server-simple-request-handler.h',
        'model/http/http-server.h',
        'model/http/http-client-collection.h',
        'model/http/http-client-basic.h',

        'model/dash/dash-common.h',
        'model/dash/dash-request-handler.h',
        'model/dash/endash-video-player.h',
        
        'model/mobility/constant-speed-zigzag-box-mobility-model.h',
        'model/propagation/log-normal-distance-propagation-loss-model.h',
        
        'helper/http-helper.h',
        'helper/endash-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

